In [2]:
import numpy as np

# Criando Arrays NumPy

In [3]:
# Array criado a partir de uma lista
arr1 = np.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [4]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(9,)

In [7]:
# Imprimindo um elemento
arr1[4]

48

In [8]:
arr1[1:4]

array([21, 32, 43])

In [9]:
# Criar uma lista de índices
indices = [1, 2, 5, 6]
arr1[indices]

array([21, 32, 15, 76])

In [10]:
# Cria um máscara booleana para os elementos
mask = (arr1 % 2 == 0)
arr1[mask]

array([10, 32, 48, 76])

In [11]:
# Aterando um elemento do array
arr1[0] = 100
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [12]:
# Não é possível incluir elemento de outro tripo
try:
  arr1[0] = 'novo elemento'
except:
  print('Operação não permitida')

Operação não permitida


# Funções NumPy

In [13]:
# Funçao array() cria um array Numpy
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2)

[1 2 3 4 5]


In [14]:
# Métodos do array Numpy
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [15]:
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [16]:
# Funçao cria um array NumPy contendo uma progressão aritimética aparti de um intervalo - start, stop, astep
arr3 = np.arange(0, 50, 3)
print(arr3)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [17]:
# Criando array com elementos zero
arr4 = np.zeros(10)
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
# Retorna matriz identidade
arr5 = np.eye(3)
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# Matriz diagonal
arr6 = np.diag(np.array([1, 2, 3, 4]))
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [20]:
# Conjutno de valores numérico
print(np.linspace(0, 10, 15))
print(np.logspace(0, 5, 10))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]
[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


# Matrizes

In [21]:
arr9 = np.array([[1,2,3], [4, 5, 6]])
print(arr9)

[[1 2 3]
 [4 5 6]]


In [22]:
type(arr9)

numpy.ndarray

In [23]:
arr9.shape

(2, 3)

In [24]:
# Criando uma matriz 2x3 com valores '1'
arr10 = np.ones((2,3))
print(arr10)

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
# Criando matriz através de listas
lista = [[13, 81, 22], [0, 34, 59], [21, 48, 94]]
arr11 = np.matrix(lista)
print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [26]:
type(arr11)

numpy.matrix

In [27]:
# Indexação da matrix
arr11[2,1]

48

In [28]:
# Indexação da matrix
arr11[0:2, 2]

matrix([[22],
        [59]])

In [29]:
# Indexação da matrix
arr11[1, ]

matrix([[ 0, 34, 59]])

In [30]:
# Alterando Elementos
arr11[0, 1] = 100
print(arr11)

[[ 13 100  22]
 [  0  34  59]
 [ 21  48  94]]


# Manipulando Objetos de 3 e 4 Dimensões com NumPy

In [31]:
# Criando array de 3 dimensões
arr_3d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

In [32]:
print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [33]:
arr_3d.ndim

3

In [34]:
arr_3d.shape

(2, 3, 4)

In [35]:
arr_3d[0, 2, 1]

10

In [36]:
# Array de 4 dimensões
arr_4d = np.array([
    [
        [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10],
            [11, 12, 13, 14, 15],
            [16, 17, 18, 19, 20]
        ],
        [
            [21, 22, 23, 24, 25],
            [26, 27, 28, 29, 30],
            [31, 32, 33, 34, 35],
            [36, 37, 38, 39, 40]
        ],
        [
            [41, 42, 43, 44, 45],
            [46, 47, 48, 49, 50],
            [21, 52, 53, 54, 55],
            [56, 57, 58, 59, 60]
        ]
    ],
    [
        [
            [61, 62, 63, 64, 65],
            [66, 67, 68, 69, 70],
            [71, 72, 73, 74, 75],
            [76, 77, 78, 79, 80]
        ],
        [
            [81, 82, 83, 84, 85],
            [86, 87, 88, 89, 90],
            [91, 92, 93, 94, 95],
            [96, 97, 98, 99, 100]
        ],
        [
            [101, 102, 103, 104, 105],
            [106, 107, 108, 109, 110],
            [111, 112, 113, 114, 115],
            [116, 117, 118, 119, 120]
        ]
    ]
])

In [37]:
print(arr_4d)

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]
   [ 21  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]]


In [38]:
arr_4d.ndim

4

In [39]:
arr_4d.shape

(2, 3, 4, 5)

In [40]:
arr_4d[0, 2, 1, 4]

50

In [41]:
arr_4d[0, 2, 1]

array([46, 47, 48, 49, 50])

# Operações com Arrays

In [50]:
# Somando arrays
arr19 = np.array([[1, 2], [3, 4]])
arr20 = np.array([[5, 6], [0, 7]])

print(arr19)
print(arr20)

[[1 2]
 [3 4]]
[[5 6]
 [0 7]]


In [51]:
# Soma de Arrays
np.add(arr19, arr20)

array([[ 6,  8],
       [ 3, 11]])

In [52]:
# Multiplicação de Matrizes
np.dot(arr19, arr20)

array([[ 5, 20],
       [15, 46]])

In [54]:
# Multiplicação de Matrizes
arr21 = arr19 @ arr20
print(arr21)

[[ 5 20]
 [15 46]]


# Slicing ou Fatiamento

In [55]:
arr22 = np.diag(np.arange(3))
print(arr22)

[[0 0 0]
 [0 1 0]
 [0 0 2]]


In [64]:
arr22.flatten()

array([0, 0, 0, 0, 1, 0, 0, 0, 2])